### ISSUE TITLE
Block Signal writes unending stream of error messages to log

### ISSUE THREAD

**Issue by Hexiram** [MineMaarten/Signals#52] opened 2017-12-05 01:55 UTC
If the rail system extends beyond the chunks that are currently loaded, the pathfinding algorithm used to determine signalling blocks will emit a rapid stream of errors. The fml-junk-earlystartup.log file can grow by multiple megabytes per minute.

Steps to reproduce:
1. Generate a new world 
2. Lay down rails in a straight line until the chunk with the starting end is unloaded
3. Turn around and place a Block Signal next to the track

**Comment by MineMaarten** [comment] 2017-12-09 09:36
I can't reproduce your chunk loading error stream, with this 400 block long rail segment:
![2017-12-09_10 20 59](https://user-images.githubusercontent.com/5345405/33794437-9564bc5c-dccc-11e7-9350-f8b8733d6f70.png)

However, I did get an error stream when I placed the signal right at the edge, but that's also with a very short piece of track:
![2017-12-09_10 21 12](https://user-images.githubusercontent.com/5345405/33794443-ac43aa3c-dccc-11e7-95a9-c7e90d068b81.png)

I got https://pastebin.com/LkTeg1pa times a million.

Can you confirm this is the issue?

**Comment by Hexiram** [comment] 2017-12-10 16:11
In my logs, some of the function names appear as net.minecraft.world.World.func_72939_s rather than net.minecraft.world.World.updateEntities, but other than that the messages I get look exactly like that.

**Comment by MineMaarten** [comment] 2017-12-10 16:19
Okay, that makes sense, as I am running in a development environment, where internal function names are deobfuscated :).

And you can also confirm this is to do with the placement of a signal right at the end, and not with chunk load boundaries? If that's the case, we can close this issue, as I've released a fix an hour ago :).

**Comment by Hexiram** [comment] 2017-12-10 16:47
Yes, it occurs when the signal is placed at the end.

The rail setup where I originally encountered this didn't have any signals placed at the very end of a track, but I seem to have placed one at a chunk boundary and the error started once I moved around and the rail in front of it unloaded.

**Comment by MineMaarten** [comment] 2017-12-10 16:49
Ahh right! That should be resolved now then yes! Thanks for the info!

**Closed by MineMaarten** 2017-12-10 16:49 UTC
Labels: bug, More info required
